# -- French main navigation --

[[main]]
  identifier = "about"
  name = "À propos"
  url = "/page/about/"
  weight = 10

[[main]]
  identifier = "archive"
  name = "Archives"
  url = "/fr/archive/"
  weight = 20

[[main]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/mmornati"
  weight = 40

[[footer]]
  identifier = "archive"
  name = "Archives"
  url = "/fr/archive/"
  weight = 10

[[footer]]
  identifier = "rss"
  name = "RSS"
  url = "/rss.xml"
  weight = 20